
namespace Forecast.Models
{
    public class ForecastSums
    {
        public string GMSVenID { get; set; }
        public string VendorDesc { get; set; }
        public string ItemID { get; set; }
        public string FiscalWk { get; set; }
        public string FiscalMo { get; set; }
        public string FiscalQtr { get; set; }
        public string MD { get; set; }
        public string MM { get; set; }
        public string Region { get; set; }
        public string District { get; set; }
        public string Patch { get; set; }
		public string Parent { get; set; }
        public string ProdGrp { get; set; }
        public string Assrt { get; set; }
        public string SalesUnits_TY { get; set; }
        public string SalesUnits_LY { get; set; }
        public string SalesUnits_2LY { get; set; }
        public string SalesUnits_FC { get; set; }
        public string SalesUnits_Var { get; set; }
        public string SalesDollars_TY { get; set; }
        public string SalesDollars_LY { get; set; }
        public string SalesDollars_2LY { get; set; }
        public string SalesDollars_FR_FC { get; set; }
        public string SalesDollars_Curr { get; set; }
        public string SalesDollars_Var { get; set; }
        public string CAGR { get; set; }
        public string Asp_TY { get; set; }
        public string Asp_LY { get; set; }
        public string Asp_FC { get; set; }
        public string Asp_Var { get; set; }
        public string RetailPrice_TY { get; set; }
        public string RetailPrice_LY { get; set; }
        public string RetailPrice_FC { get; set; }
        public string RetailPrice_Var { get; set; }
        public string RetailPrice_Erosion_Rate { get; set; }
        public string SalesDollars_FR_TY { get; set; }
        public string SalesDollars_FR_LY { get; set; }
        public string MarginDollars_FR_TY { get; set; }
        public string MarginDollars_FR_LY { get; set; }
        public string MarginDollars_FR_Var { get; set; }
        public string Cost_TY { get; set; }
        public string Cost_LY { get; set; }
        public string Cost_FC { get; set; }
        public string Cost_Var { get; set; }
        public string Margin_Dollars_TY { get; set; }
        public string Margin_Dollars_LY { get; set; }
        public string Margin_Dollars_Curr { get; set; }
        public string Margin_Dollars_FR { get; set; }
        public string Margin_Dollars_Var_Curr { get; set; }
        public string Margin_Percent_TY { get; set; }
        public string Margin_Percent_LY { get; set; }
        public string Margin_Percent_Curr { get; set; }
        public string Margin_Percent_FR { get; set; }
        public string Margin_Percent_Var { get; set; }
        public string Turns_TY { get; set; }
        public string Turns_LY { get; set; }
        public string Turns_FC { get; set; }
        public string Turns_Var { get; set; }
        public string SellThru_TY { get; set; }
        public string SellThru_LY { get; set; }
        public string Dollars_FC_DL { get; set; }
        public string Dollars_FC_LOW { get; set; }
        public string Dollars_FC_Vendor { get; set; }
        public string Units_FC_DL { get; set; }
        public string Units_FC_LOW { get; set; }
        public string Units_FC_Vendor { get; set; }
        public string Dollars_FC_DL_Var { get; set; }
        public string Dollars_FC_LOW_Var { get; set; }
        public string Dollars_FC_Vendor_Var { get; set; }
        public string Units_FC_DL_Var { get; set; }
        public string Units_FC_LOW_Var { get; set; }
        public string Units_FC_Vendor_Var { get; set; }
        public string ReceiptUnits_TY { get; set; }
        public string ReceiptUnits_LY { get; set; }
        public string ReceiptDollars_TY { get; set; }
        public string ReceiptDollars_LY { get; set; }
        public string PriceSensitivityImpact { get; set; }
        public string PriceSensitivityPercent { get; set; }
        public string VBUPercent { get; set; }
        public string MM_Comments { get; set; }
        public string Vendor_Comments { get; set; }
    }
}