namespace Forecast.E2ETests.Global.Models
{
    public class ForecastTableRow
    {
        public string ForecastID { get; set; }
        public string VendorDesc { get; set; }
        public int ItemID { get; set; }
        public string ItemDesc { get; set; }
        public string ItemConcat { get; set; }
        public int FiscalWk { get; set; }
        public int FiscalMo { get; set; }
        public int FiscalQtr { get; set; }
        public string MD { get; set; }
        public string MM { get; set; }
        public string Region { get; set; }
        public string District { get; set; }
        public string Patch { get; set; }
        public string ParentID { get; set; }
        public string ParentDesc { get; set; }
        public string ParentConcat { get; set; }
        public int ProdGrpID { get; set; }
        public string ProdGrpDesc { get; set; }
        public string ProdGrpConcat { get; set; }
        public int AssrtID { get; set; }
        public string AssrtDesc { get; set; }
        public string AssrtConcat { get; set; }
        public int SalesUnits_TY { get; set; }
        public int SalesUnits_LY { get; set; }
        public int SalesUnits_2LY { get; set; }
        public int SalesUnits_FC { get; set; }
        public double SalesUnits_Var { get; set; }
        public double SalesDollars_TY { get; set; }
        public double SalesDollars_LY { get; set; }
        public double SalesDollars_2LY { get; set; }
        public double SalesDollars_FR_FC { get; set; }
        public double SalesDollars_Curr { get; set; }
        public double SalesDollars_Var { get; set; }
        public int CAGR { get; set; }
        public double Asp_TY { get; set; }
        public double Asp_LY { get; set; }
        public double Asp_FC { get; set; }
        public double Asp_Var { get; set; }
        public double Cogs_TY { get; set; }
        public double Cogs_LY { get; set; }
        public int Cogs_FC { get; set; }
        public int Cogs_Var { get; set; }
        public double RetailPrice_TY { get; set; }
        public double RetailPrice_LY { get; set; }
        public double RetailPrice_FC { get; set; }
        public double RetailPrice_Var { get; set; }
        public double Cost_TY { get; set; }
        public double Cost_LY { get; set; }
        public double Cost_FC { get; set; }
        public double Cost_Var { get; set; }
        public double Margin_Dollars_TY { get; set; }
        public double Margin_Dollars_LY { get; set; }
        public double Margin_Dollars_Curr { get; set; }
        public double Margin_Dollars_FR { get; set; }
        public double Margin_Dollars_Var_Curr { get; set; }
        public double Margin_Percent_TY { get; set; }
        public double Margin_Percent_LY { get; set; }
        public double Margin_Percent_Curr { get; set; }
        public double Margin_Percent_FR { get; set; }
        public double Margin_Percent_Var { get; set; }
        public double GMROI_TY { get; set; }
        public double GMROI_LY { get; set; }
        public double GMROI_FC { get; set; }
        public double GMROI_Var { get; set; }
        public double Turns_TY { get; set; }
        public double Turns_LY { get; set; }
        public double Turns_FC { get; set; }
        public double Turns_Var { get; set; }
        public double SellThru_TY { get; set; }
        public double SellThru_LY { get; set; }
        public double Dollars_FC_DL { get; set; }
        public double Dollars_FC_LOW { get; set; }
        public double Dollars_FC_Vendor { get; set; }
        public int Units_FC_DL { get; set; }
        public int Units_FC_LOW { get; set; }
        public int Units_FC_Vendor { get; set; }
        public double Dollars_FC_DL_Var { get; set; }
        public double Dollars_FC_LOW_Var { get; set; }
        public double Dollars_FC_Vendor_Var { get; set; }
        public double Units_FC_DL_Var { get; set; }
        public double Units_FC_LOW_Var { get; set; }
        public double Units_FC_Vendor_Var { get; set; }
        public int ReceiptUnits_TY { get; set; }
        public int ReceiptUnits_LY { get; set; }
        public double ReceiptDollars_TY { get; set; }
        public double ReceiptDollars_LY { get; set; }
        public string PriceSensitivityImpact { get; set; }
        public string PriceSensitivityPercent { get; set; }
        public string MM_Comments { get; set; }
        public string Vendor_Comments { get; set; }
    }
}
